spring.application.name=backend
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:18282/railwaymaglev.proxy.rlwy.net:18282/railway
spring.datasource.username=root
spring.datasource.password=KxGvmvhrxvYoFVifxfnXgSaApWSVHKhq
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8081}
spring.jpa.open-in-view=false
